library enums;

enum ReturnStatus {
  SUCCESS,
  ERROR,
  ERROR_WEAK_PASSWORD,
  ERROR_INVALID_EMAIL,
  ERROR_EMAIL_ALREADY_IN_USE,
  ERROR_WRONG_PASSWORD,
  ERROR_USER_NOT_FOUND,
  ERROR_USER_DISABLED,
  ERROR_TOO_MANY_REQUESTS,
  ERROR_OPERATION_NOT_ALLOWED,
}